version: '3'
services:
  mysqldb:
    ports:
      - "3306:3306"
    container_name: mysqldb
    image: mysql:8.1.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=strava_db
